scrape_configs:
  - job_name: "chat_dog_classification"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"
